# Generated by Django 5.2.4 on 2025-08-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=20)),
                ("lname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField()),
            ],
        ),
    ]
