# Generated by Django 5.2.4 on 2025-08-06 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="short_description",
            new_name="information",
        ),
    ]
