# Generated by Django 5.2.4 on 2025-08-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_short_description_products_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
